language: android
dist: trusty
jdk: oraclejdk8

before_install:
  # Download SDK
  - yes | sdkmanager "tools" &>/dev/null
  - yes | sdkmanager "platform-tools" &>/dev/null
  - yes | sdkmanager "build-tools;29.0.3" &>/dev/null
  - yes | sdkmanager "platforms;android-29" &>/dev/null
  # Update remaining dependencies and accept licenses
  - yes | sdkmanager --update &>/dev/null
  - yes | sdkmanager --licenses &>/dev/null
  # Copy keystore files
  - echo "$DEBUG_KEYSTORE_FILE_BASE_64" | base64 --decode > "$HOME/.android/debug.keystore"
  - echo "$RELEASE_KEYSTORE_FILE_BASE_64" | base64 --decode > sample/keystore.jks
  - touch local.properties
  - echo "storePassword=$RELEASE_KEYSTORE_STORE_PASSWORD" >> local.properties
  - echo "keyAlias=$RELEASE_KEYSTORE_KEY_ALIAS" >> local.properties
  - echo "keyPassword=$RELEASE_KEYSTORE_KEY_PASSWORD" >> local.properties
  # Copy secret key ring for file signature
  - echo "$SECRET_KEY_RING_FILE_BASE_64" | base64 --decode > "$HOME/secring.gpg"
  - echo "signing.secretKeyRingFile=$HOME/secring.gpg" >> gradle.properties
  - echo "signing.keyId=$SIGNING_KEY_ID" >> gradle.properties
  - echo "signing.password=$SIGNING_PASSWORD" >> gradle.properties
  # Copy secret keys to gradle.properties
  - echo "MATERIAL_PREFERENCE_PLAY_STORE_BASE_64_PUBLIC_KEY=$PLAY_STORE_BASE_64_PUBLIC_KEY" >> gradle.properties
  - echo "SONATYPE_NEXUS_USERNAME=$OSS_SONATYPE_NEXUS_USERNAME" >> gradle.properties
  - echo "SONATYPE_NEXUS_PASSWORD=$OSS_SONATYPE_NEXUS_PASSWORD" >> gradle.properties

script: ./gradlew clean build --stacktrace

after_success:
  - echo "Build success"
#  - .buildscript/deploy_snapshot.sh

env:
  global:
    - ANDROID_SDK_ROOT=/usr/local/android-sdk/

branches:
  except:
    - gh-pages

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache